apiVersion: v1
kind: Pod
metadata:
  name: ingress-controller
spec:
  containers:
  - name: ingress-controller
    image: bitnami/nginx-ingress-controller:1.0.0
    ports: 
    - containerPort: 80
    resources:
      requests:
        cpu: "1"
        memory: "256Mi"
      limits:
        cpu: "2.5"
        memory: "1024Mi"