## 2. Create a ClusterRole with the name api-clusterrole, 
# and create a ClusterRoleBinding named api-clusterrolebinding. 
# Map the ServiceAccount from the previous step to the API resources pods 
# with the operations watch, list, and get.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["watch", "list", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-clusterrolebinding
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-clusterrole
subjects:
- kind: ServiceAccount
  name: api-access
  namespace: apps