## 1. Create the ServiceAccount named api-access in a new namespace called apps.
apiVersion: v1
kind: Namespace
metadata:
  name: apps

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-access
  namespace: apps


